config/routes.rb
Rails.application.routes.draw do
  resources :programs
  resources :flags
  resources :tracks
  resources :people
  resources :conferences

  root 'conferences#index'

end

app/models/program.rb
class Program < ActiveRecord::Base
  has_and_belongs_to_many :flags
  has_and_belongs_to_many :tracks
  has_and_belongs_to_many :people
  belongs_to :conference
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(
        :start_date, :start_time, :title, :subtitle, :activity_type,
        :short_description, :long_description, :loc, :mins, :conference_id)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :activity_type %><br>
    <%= f.text_field :activity_type %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_field :short_description %>
  </div>
  <div class="field">
    <%= f.label :long_description %><br>
    <%= f.text_area :long_description %>
  </div>
  <div class="field">
    <%= f.label :loc %><br>
    <%= f.text_field :loc %>
  </div>
  <div class="field">
    <%= f.label :mins %><br>
    <%= f.number_field :mins %>
  </div>
  <div class="field">
    <%= f.label :conference_id %><br>
    <%= f.text_field :conference_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Programs</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>Start time</th>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Activity type</th>
      <th>Short description</th>
      <th>Long description</th>
      <th>Loc</th>
      <th>Mins</th>
      <th>Conference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.start_date %></td>
        <td><%= program.start_time %></td>
        <td><%= program.title %></td>
        <td><%= program.subtitle %></td>
        <td><%= program.activity_type %></td>
        <td><%= program.short_description %></td>
        <td><%= program.long_description %></td>
        <td><%= program.loc %></td>
        <td><%= program.mins %></td>
        <td><%= program.conference %></td>
        <td><%= link_to 'Show', program %></td>
        <td><%= link_to 'Edit', edit_program_path(program) %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @program.start_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @program.start_time %>
</p>

<p>
  <strong>Title:</strong>
  <%= @program.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @program.subtitle %>
</p>

<p>
  <strong>Activity type:</strong>
  <%= @program.activity_type %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @program.short_description %>
</p>

<p>
  <strong>Long description:</strong>
  <%= @program.long_description %>
</p>

<p>
  <strong>Loc:</strong>
  <%= @program.loc %>
</p>

<p>
  <strong>Mins:</strong>
  <%= @program.mins %>
</p>

<p>
  <strong>Conference:</strong>
  <%= @program.conference %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>